services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
   
  basketdb:
    container_name: basketdbd
    restart: always
    ports:
      - "6379:6379" 

  catalogapi:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"

  basketapi:
    container_name: Basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "CacheSettings:ConnectionStrings=basketdb:6379"   
    depends_on:
     - basketdb
    ports:
      - "8081:8080"

