services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogApi/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/BasketApi/Dockerfile

volumes:
  mongo_data:


